---
title: "MP read mapping plots"
output: html_notebook
---

Import libraries...
```{r}
library(ggplot2)
library(data.table)
library(viridis)
```
Set path variables...
```{r}
setwd("C:/Users/kerst/Desktop/MP/")
directory <- "results"
mappers <- c("star","hisat","crac","contextmap2")
error_rate <- 0
samples <- c("subsample_01","subsample_02","subsample_03")
filename <- "summary.csv"

```
Read the data..
```{r}
summary_list <- lapply(mappers,function(mapper){
  rbindlist(lapply(samples,function(sample){
    data <- fread(file.path(directory,paste("error",error_rate,mapper,sample,sep="_"),filename))
    data$mapper <- mapper
    data$sample <- sample
    return(data)
    }))
})
summary <- rbindlist(summary_list)
```
Define functions...
```{r}
recall <- function(tp,fn){
  return(tp/(tp+fn))
}
precision <- function(tp,fp){
  return(tp/(tp+fp))
}
```
```{r}
summary <-summary[summary$sample=="subsample_01"]
```


Plotting level: read pairs, range correct
```{r}
ggplot(summary,aes(x=n_correct_range_pairs/n_proper_pairs,y=n_correct_range_pairs/n_pairs,color=mapper,shape=mapper))+
  geom_point(size=3)+
  labs(x="Correct pairs / mapped pairs",y="Correct pairs / all pairs",title=paste("Error rate:",error_rate,"Level: Read pairs with correct range"),color="Mapping tool",shape="Mapping tool")+
  theme_bw()+
  theme(plot.title = element_text(size=13.5))
```

Plotting level: read pairs with all junctions correct
```{r}
ggplot(summary,aes(x=n_all_junctions_correct_pairs/n_proper_pairs,y=n_all_junctions_correct_pairs/n_pairs,color=mapper,shape=mapper))+
  geom_point(size=3)+
  labs(x="Correct pairs / mapped pairs",y="Correct pairs / all pairs",title=paste("Error rate:",error_rate,"Level: Read pairs with all junctions mapped correctly"),color="Mapping tool",shape="Mapping tool")+
  theme_bw()+
  theme(plot.title = element_text(size=13.5))
```
```{r}
ggplot(summary,aes(x=n_all_junctions_correct_pairs/n_proper_pairs,y=n_proper_pairs/n_pairs,color=mapper,shape=mapper))+
  geom_point(size=3)+
  labs(x="Correct pairs / mapped pairs",y="mapped pairs / all pairs",title=paste("Error rate:",error_rate,"Level: Read pairs with all junctions mapped correctly"),color="Mapping tool",shape="Mapping tool")+
  scale_color_viridis(discrete = TRUE, option = "C")+
  theme_bw()+
  theme(plot.title = element_text(size=13.5))
```

Plotting level: junctions with correct range
```{r}
ggplot(summary,aes(x=precision(n_correct_junctions,n_false_junctions),
                   y=recall(n_correct_junctions,n_junctions-n_correct_junctions),
                   color=mapper,shape=mapper))+
  geom_point(size=3)+
  labs(x="Precision",y="Recall",title=paste("Error rate:",error_rate,"Level: Junctions with correct range"),color="Mapping tool",shape="Mapping tool")+
  theme_bw()+
  theme(plot.title = element_text(size=13.5))
```
Make data long...
```{r}
summary_long <- melt(summary,id.vars = "mapper",variable.name = "type",value.name = "count")
summary_long[,count:=as.integer(count)]
```
```{r}
ggplot(summary_long,aes(x=type,y=count,fill=mapper))+
  geom_bar(stat = "identity",position = "dodge")+
  scale_color_viridis(discrete = TRUE, option = "D")+
  scale_fill_viridis(discrete = TRUE, option = "D")+
  theme_bw()+
    theme(axis.text.x = element_text(angle = 90))
```
```{r}
fractions_pairs<-data.table(mapper=summary$mapper)
fractions_pairs[,unmapped:=summary$n_pairs-summary$n_proper_pairs]
fractions_pairs[,"mapped correctly":=summary$n_all_junctions_correct_pairs]
fractions_pairs[,"mapped incorrectly":=summary$n_proper_pairs-summary$n_all_junctions_correct_pairs]
fractions_pairs <- melt(fractions_pairs,id.vars = "mapper", variable.name ="type",value.name = "count" )
```
```{r}
ggplot(fractions_pairs,aes(x=mapper,y=count,fill=type))+
  geom_bar(stat="identity")
  
```

